#!/bin/bash

cd "$DOTPATH"

for file in .??*; do
  if [[ "$file" == ".git" ]]; then
    continue
  fi
  mv "$HOME/$file" "$HOME/$file.orig"
  ln -snvf "$DOTPATH/$file" "$HOME/$file"
done

source ~/.bash_profile
