#!/bin/bash

. "$DOTPATH"/etc/install -l
. "$DOTPATH"/etc/lib/package

print_header "Install Git client"
if is_installed "git"; then
  print_done "Git is already installed!"
  print_info "Skip install task."
  return 
fi

install git
print_success "Git client has been installed."

