#!/bin/bash

. "$DOTPATH"/etc/install -l
. "$DOTPATH"/etc/lib/ask
. "$DOTPATH"/etc/lib/package

print_header "Install Ruby with rbenv"

# Build Essentials
print_info "Install build tools..."

install gcc
install make
install gcc-c++ g++
install bzip2
# ruby-build suggested build environment
install openssl-devel libssl-dev
install libyaml-devel libyaml-dev
install libffi-devel libffi-dev
install ncurses-devel libnucurses5-dev
install readline-devel libreadline6-dev
install gdbm-devel libgdbm-dev
install zlib-devel zlib1g-dev

if [ -n "$(command -v yum)" ]; then
  install readline-devel
  install zlib-devel
else
  install autoconf
  install bison
  install build-essential
  install libgdbm3
fi

# rbenv
print_info "Install rbenv"

git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
. ~/.bash_profile


# Ruby
print_info "Install Ruby"

CONFIGURE_OPTS="--disable-install-rdoc" rbenv install 2.3.1 -v
rbenv rehash
rbenv global 2.3.1
ruby -v

# if ask "Install bundler gem?"; then
  gem install bundler --no-ri --no-rdoc
# fi

print_success "Ruby has been installed."

