#!/bin/bash

. "$DOTPATH"/etc/install -l
. "$DOTPATH"/etc/lib/package

print_header "Install vim (custom build)"

# Build Essentials
print_info "Install build tools..."

install lua
install lua-devel
install ncurses-devel
install hg


print_info "Pulling vim sources from Google Code."

hg clone https://vim.googlecode.com/hg vim
cd vim
hg pull
hg update


print_info "Building..."

make distclean
make clean
./configure --prefix=/usr/local \
         --enable-multibyte --with-features=huge \
         --enable-luainterp --with-lua-prefix=/usr \
         --enable-rubyinterp=yes \
         --enable-cscope --enable-fail-if-missing

make


print_info "Install"

sudo make install


print_info "Install NeoBundle"
cd ..
curl https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh | sh

print_success "vim has been installed."

