#!/bin/bash

. "$DOTPATH"/etc/install -l
. "$DOTPATH"/etc/lib/package

print_header "Install vim (custom build)"

# Build Essentials
print_info "Install build tools..."

install lua lua5.1
install lua-devel liblua5.1-dev
install ncurses-devel libncurses5-dev


print_info "Pulling vim sources from GitHub."

git clone https://github.com/vim/vim.git
cd vim
git pull

print_info "Building..."

make distclean
make clean
./configure --prefix=/usr/local \
         --enable-multibyte --with-features=huge \
         --enable-luainterp --with-lua-prefix=/usr \
         --enable-rubyinterp=yes \
         --enable-cscope --enable-fail-if-missing

make


print_done "Install"

sudo make install


print_info "Install NeoBundle"
cd ..
curl https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh | sh

print_success "vim has been installed."

